version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    environment:
      MOSQUITTO_CONF_FILE: /mosquitto/config/mosquitto_annon.conf
    ports:
      - 1884:1883
      - 8883:8883
      - 9001:9001
    extra_hosts:
      mosquittobroker: 127.0.0.1